### ISSUE TITLE
shared data files between papers

### ISSUE THREAD

**Issue by svenmh** [svenmh/YeastPhenome.org#1]
> 19466415 - Says data was loaded but not in either code_130304_load_data.m or code_141120_load_data_part2.m files. Plus the 2009_Watanabe~Ohya directory is empty.  Should this even be marked loaded?

The private notes field says "Dataset same as Ohya~Morishita, 2005" -- so this is just to say that we've processed this paper and the data is available. It probably makes sense to duplicate the data from Ohya~Morishita & load it in the database (+ provide the corresponding raw data files).

**Comment by abarysh** [comment]
I solved this issue via replicating the data and making the 2 datasets independent from each other.
