### ISSUE TITLE
The text for the About page

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#11]
YeastPhenome.org collects phenotypic data derived from systematic screens of large-scale mutant collections in budding yeast Saccharomyces cerevisiae. Our goal is to study the relationship between different mutant phenotypes and integrate them into mapping of the functional organization of biological pathways.

We are interested in both quantitative and qualitative phenotypes, as long as, for a given study, the data were collected systematically and for a large number of mutants.

Our primary source of data are the supplementary materials of the relevant publications. On top of that, many authors have contributed more complete and previously unpublished versions of their datasets (e.g., raw quantitative values from which the published hit list was derived). These datasets will be specifically flagged to emphasize their special status.

As of today, we are at the data gathering stage. The plan is to collect, organize and share in a standardized format all of the phenotypic data obtained by the yeast community. Updates on progress will be released via this website.

Yeastphenome.org was created and is being maintained at Princeton University by:

- Anastasia Baryshnikova (principal investigator, www.baryshnikova-lab.org)
- Sven Heinicke (database and website support)
- Fan Kang (database support)
- Mark Schroeder (server support)
- Rose Oughtred (literature curator)
- Christie Chang (literature curator)
- Brianna Richardson (undergraduate student)

**Comment by svenmh** [comment]
Tried to make the bold items look like the home page too.
