### ISSUE TITLE
Remove "data" info from homepage

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#13]
Let's remove all the info about the number of data points from the homepage (for now). I'm not 100% it's accurate at this point, so we should just leave them out. This includes:

- "0 have data"
- both "Most studied phenotype" and "Most studied experimental condition".

**Comment by svenmh** [comment]
The requested items have been removed.  They can still be seen in verbose mode.

They believe they are registering as zero because we left the `papers_data` table blank.
