### ISSUE TITLE
"Download Data" sometimes present and sometimes not

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#15]
For example:

http://yeastphenome-dev.princeton.edu/papers/6/ -- absent
http://yeastphenome-dev.princeton.edu/papers/289/ -- present but yellow and not active

Is there a particular reason it's like this? I think the button should always be present but (like I said in a previous issue) greyed out when there's nothing to download.

**Comment by svenmh** [comment]
If an item doesn't have an item the database doesn't think there is any data to be downloaded.  And in the case of papers/6 it doesn't have any date to download in the repo.

the yellow button means that the database thinks there is data to download, but no files are found in the repo.  These are related to the issues in:  https://github.com/abarysh/Yeastphenome.org-Loading-data/issues.

Should of explained this in the issue where I made these choices.

**Comment by abarysh** [comment]
Could we make the button grey in both cases? I.e., whenever the user cannot download the data (for whatever reason), the button should be grey. I think having 2 colors just makes it more difficult to guess what's happening (for the user).
