### ISSUE TITLE
Info from Pubmed on the Papers detail page

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#20]
We should try to add a few more details about each paper onto the papers detail page. Ideally, the page would be like this:

FirstAuthor~LastAuthor, Year
PMID: ...
Title:
Full author list:
Citation:
Abstract:

Table with list of datasets (as it is now).

**Comment by svenmh** [comment]
I was hoping to AJAX this stuff down with: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2904758/ but that service seems to have disappeared.  Might cache MEDLINE entries locally instead.

**Comment by abarysh** [comment]
We might consider storing that data in the database.. whatever will make it work faster for the users.

**Comment by svenmh** [comment]
This feature is up on dev and ready for comments.

**Comment by abarysh** [comment]
It looks like it's taking a long time to get the info: besides "Title" "authors" "abstract" I see hourglasses and not much else happens (for several minutes).

**Comment by svenmh** [comment]
Really, never takes make then a few seconds for me, and I'm working from home.  Humph.  Can you shift-reload?  Maybe something not refreshing.

**Comment by abarysh** [comment]
It's a Safari thing. Works great in Chrome. And it looks great. The only thing: Citation should include the name of the journal, the year, volume(issue) and the pages. Right now it looks like it's only showing the full publication date (year, month and day)

**Comment by svenmh** [comment]
Was broken on firefox too, fixed that, hopefully it was the same thing.  Will check at home.

**Comment by abarysh** [comment]
Yep, works on safari now too. Great!

**Comment by svenmh** [comment]
I think this is all done.  If you like it close this issue please.

**Comment by abarysh** [comment]
Looks great. Just a couple of comments before we close it: 1) for some reason, the dots that separated the authors are no longer visible. I'm not sure if this is intentional or a bug, but I thought they looked really nice yesterday. Could we put them back, if possible? 2) Let's just call it "Authors" instead of "Full author list" 3) Can we leave less empty space on the right? Ideally, the left boundary of the text in the first column would be aligned with the left boundary of the title (while the text itself in the first column is aligned to the right -- I hope this makes sense).

**Comment by svenmh** [comment]
It is now standard bootstrap dl-horizontal spacing on the left.  Do you want it smaller?

**Comment by abarysh** [comment]
You know what? let's leave it as it is. I don't want to mess around with bootstrap's standard design. I think it looks great.
