### ISSUE TITLE
Acknowledge people on the Papers detail page

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#21]
Whenever the source for tested genes or data for at least 1 dataset in a paper is labelled as "personal communication" and a person is listed, that person should be acknowledged on the Papers detail page.

For example:

The list of tested genes was kindly provided by: ...
The data was kindly provided by: ...

**Comment by svenmh** [comment]
this has been added.

**Comment by abarysh** [comment]
Cool! Can we specify whether it's the data or the list of tested genes that were provided? E.g., for Chesi A~Gitler AD, 2012 both were provided. But for Stepchenkova EI~Pavlov YI, 2005 it was only the list of tested strains.

**Comment by svenmh** [comment]
OK, check it out.

**Comment by abarysh** [comment]
Yep, looks cool. I would write a bit more explicitly: "The most complete dataset and the list of tested genes for this publication were kindly provided ...". And then, the individual acknowledgements too: "The most complete dataset for this publication was ..." and "The list of tested genes for this publication was ..." .

**Comment by svenmh** [comment]
try again.

**Comment by abarysh** [comment]
perfect!
