### ISSUE TITLE
Add a navigation bar with a search box to every page

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#22]
Bootstrap makes it very easy to add a standard navigation bar with a search box to every page. 

http://getbootstrap.com/components/#navbar

We could have something like:

YeastPhenome.org     Papers    Phenotypes    Conditions                             [Search box] Submit

**Comment by svenmh** [comment]
my first attempt at a navbar is up on http://yeastphenome-dev.princeton.edu/, will clean it up a bit more tomorrow.

**Comment by abarysh** [comment]
I like it a lot. A couple of suggestions: could we push the bar all the way to the top, so that there's no space between the bar and the top of the page? And make it more clear which section is currently active? Something like here: http://www.crossdictionary.com/about/ (this is a side project I worked on with my parents, I got to play with Django & bootstrap a bit).

**Comment by svenmh** [comment]
It's now stuck to top, will do more tomorrow.

**Comment by svenmh** [comment]
Is it good now?

**Comment by abarysh** [comment]
Looks great. 2 more suggestions: align the "Yeastphenome" to the left margin of the text/table in the body of the page and the "Submit" button the right margin. This way it will look cleaner. And also, we probably want the search box to be a little longer and higher (I think there's a class in bootstrap to make it look analogous to the Submit button).

**Comment by svenmh** [comment]
I think it's good now.  I make the search form collapse into it's own button, plus the navbar no longer does an unwanted wrap on a viewport around 900px wide.

**Comment by abarysh** [comment]
Yep, wonderful! Just for consistency, can we make the placeholder "Search" (instead of "search")? Otherwise, this is done!
