### ISSUE TITLE
Simplified dataset table for the Papers, Phenotypes and Conditions detail pages

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#23]
The dataset table on the Papers, Phenotypes and Conditions detail pages should be structured as follows:

Papers:
Phenotype    Conditions    Collection   Tested space    Data type
growth           MMS 0.02%    hapa          1646 genes     quantitative

Phenotypes and Conditions:
same as above, except for the first 2 columns

Phenotypes:
Paper     Conditions

Conditions:
Paper    Phenotypes

**Comment by svenmh** [comment]
For "Data type" do you want what's currently under "Measured" or "Published"?

**Comment by abarysh** [comment]
It should be what's under "Available" (i.e., the ultimate data we have in our system).

**Comment by svenmh** [comment]
Does the papers page look how you like?

**Comment by abarysh** [comment]
Yep! A couple of comments:
- Should be "Collection" instead of "Collected"
- Let's say "Tested genes" instead of "Tested space" (I realize that it's not clear what's the unit of measurement for the number, so it's not clear what the number represents)
- "Data Type" should be changed to "Data type" for consistency

I noticed you added the breadcrumbs and they look great. But I think we still need the title on every page. Can we do the following?
- Keep the breadcrumbs but only to the second last step. E.g., on http://yeastphenome-dev.princeton.edu/conditions/84/ it would be "Conditions /"
- Put the title of the page underneath and big (as a standard <h1> style)
- The breadcrumbs can be on white background (not grey). We can use white space to separate them visually from the navbar and the title.

**Comment by abarysh** [comment]
Oops .. something got formatted funny in the previous comment. What I meant was "as a standard H1 style".

**Comment by svenmh** [comment]
I'll revisit the title issue when working on issue #20.

Also, I just used the breadcrumbs tag from: http://getbootstrap.com/components/#breadcrumbs

which by default changes the background.  Again, will play around with that is issue #20.

**Comment by abarysh** [comment]
Sounds good

**Comment by svenmh** [comment]
Ok, see if condition and phenotype pages look good.

**Comment by abarysh** [comment]
Yep, wonderful.
