### ISSUE TITLE
Admin site: "+" links for foreign key raw_id_fields are missing

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#24]
![admin_site_plus_missing](https://cloud.githubusercontent.com/assets/11416566/9971262/82dc1b7c-5e28-11e5-8bec-a6274715503b.jpg)

I took a screenshot of the page: Conditionset, Phenotype, Tested source and Data source fields should have a "+" link such that new connections to, e.g., existing phenotypes can be made without knowing their ID ahead of time. The Collection field (which is represented by the default <select> tool) has the "+" symbol, as expected.

**Comment by svenmh** [comment]
All 4 of those options seem to have been explicitly made raw by hand, but should be back now.

**Comment by abarysh** [comment]
Actually, they should be raw (the complete list is very long and slows down the loading of the page) but there should still be a magnifying glass next to them (to search for the right entry, instead of just typing it in yourself). It's not clear why it wasn't there before, I think that's the default appearance of raw_id fields.

**Comment by svenmh** [comment]
This seems to be a 'feature' of 1.8.  Not giving up yet.

**Comment by abarysh** [comment]
Other pages where this should be fixed:

http://yeastphenome-dev.princeton.edu/admin/conditions/conditionset/396/ (phenotype, tested source, data source)
http://www.yeastphenome.org/admin/phenotypes/observable2/5/ (Ancestry)

**Comment by svenmh** [comment]
I fixed it on the conditionset items, but the Ancestry is done differently.  Well need more investigation.
