### ISSUE TITLE
Title + About

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#25]
Just a couple of minor esthetics things:

- Let's make the title of the page nice & large (a regular H1 style). Maybe we don't need breadcrumbs for the time being. The website is pretty shallow for now, so navigation should not be impaired.

- Let's move the "About" link to the navbar. Let's place it right next to the search box, on the left. Not sure how it's going to look like but let's try.

**Comment by svenmh** [comment]
Whet you say 'title' do you mean: Paper, Phenotypes, Experimental conditions, and About?

**Comment by abarysh** [comment]
What I meant was: all pages should look like this one (currently): http://yeastphenome-dev.princeton.edu/about/
The title ("About", in this case) nice and visible. Without any background.

**Comment by svenmh** [comment]
Ok, it's up.

**Comment by abarysh** [comment]
Perfect!
