### ISSUE TITLE
Error on graphics page on yeastphenome.org

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#27]
When accessing this http://www.yeastphenome.org/phenotypes/bubble/ , I get the error:

DataError at /phenotypes/bubble/
invalid input syntax for integer: "001."
LINE 1: ...le2" WHERE "phenotypes_observable2"."parent_id" = E'001.' OR...
                                                             ^
Request Method:	GET
Request URL:	http://www.yeastphenome.org/phenotypes/bubble/
Django Version:	1.8
Exception Type:	DataError
Exception Value:	
invalid input syntax for integer: "001."
LINE 1: ...le2" WHERE "phenotypes_observable2"."parent_id" = E'001.' OR...
                                                             ^
Exception Location:	/usr/local/python/2.7.9/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/db/backends/utils.py in execute, line 64
Python Executable:	/usr/bin/python
Python Version:	2.7.9
Python Path:	
['/var/www/wsgi-bin',
 '/var/www/wsgi-bin/yeastphenome',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages/setuptools-15.1-py2.7.egg',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages/pip-6.1.1-py2.7.egg',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages/Django-1.8-py2.7.egg',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages/django_google_analytics-1-py2.7.egg',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages/django_mptt-0.7.3-py2.7.egg',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages/setuptools-15.1-py2.7.egg',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages/django_mptt-0.7.3-py2.7.egg',
 '/usr/local/python/2.7.9/lib/python27.zip',
 '/usr/local/python/2.7.9/lib/python2.7',
 '/usr/local/python/2.7.9/lib/python2.7/plat-linux2',
 '/usr/local/python/2.7.9/lib/python2.7/lib-tk',
 '/usr/local/python/2.7.9/lib/python2.7/lib-old',
 '/usr/local/python/2.7.9/lib/python2.7/lib-dynload',
 '/usr/local/python/2.7.9/lib/python2.7/site-packages']
Server time:	Mon, 23 Nov 2015 11:04:39 -0500

**Comment by svenmh** [comment]
That said, I fixed this but it rebroke #26.
