### ISSUE TITLE
Add a README file (attached) to each data ZIP

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#29]
I figured we should explain to the users what are contents of the ZIP file they download. Is there a way to add this README file to each zipped data folder? It's the same file for everyone. Ideally, we would only store 1 copy of this file somewhere where I can easily edit it (as time goes by, I will provide more/less details) and include it dynamically in each download. Is that possible?

Also, Github wouldn't let me attach an *.md file so I had to attach a *.txt extenstion. But we can strip it for the download and leave the file just as "README.md". Let me know if that works!

[README.md.txt](https://github.com/svenmh/YeastPhenome.org/files/57274/README.md.txt)

**Comment by svenmh** [comment]
Will do that Thursday morning. Child getting braces Thursday afternoon so if it's not on dev by noon it will have to wait until Friday.


Sent from my Samsung Galaxy Reverb.



-------- Original message --------

**Comment by svenmh** [comment]
is it ok to check the README.me file into Yeastphenome.org-Loading-data 
repo?

**Comment by abarysh** [comment]
Yep, for sure

**Comment by svenmh** [comment]
Ok, this is up yp-dev

**Comment by abarysh** [comment]
Yep, works great
