### ISSUE TITLE
Updates to data.zip files not visible after ~20 hours

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#30]
I updated a few datasets yesterday (e.g., PMID 12543677, PMID 19300474) but I don't see the changes in the files that are currently downloadable from either yeastphenome or yeastphenome-dev. Does the cron job run every hour? Or less often?

**Comment by svenmh** [comment]
It currently updates at 1:13 AM.  Please suggest timing.

**Comment by abarysh** [comment]
So we should be able to see the changes from yesterday, right? I made the changes around 3-5 pm on Dec. 10.

**Comment by svenmh** [comment]
From github.com:abarysh/Yeastphenome.org-Loading-data
   9747f59..7017186  master     -> origin/master
The following files downloaded last night, the README.md was from me.  Was something else meant to be there?

Updating 9747f59..7017186
Fast-forward
 Datasets/16582425/code.m                 |   28 ++++++++++++++------
 Datasets/16582425/hancock_lopes_2006.mat |  Bin 17696 -> 17152 bytes
 Datasets/README.md                       |   40 ++++++++++++++++++++++++++++++
 3 files changed, 59 insertions(+), 9 deletions(-)
 create mode 100644 Datasets/README.md

**Comment by abarysh** [comment]
Oops, my bad, I committed but forgot to push the changes. Never mind! thanks!
