### ISSUE TITLE
Update phenotype description on paper detail page

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#31]
Right now, on the condition list page (http://www.yeastphenome.org/conditions/) the phenotypes are listed with both their main denomination and their more specific variant (e.g., "growth (lag phase)", where "growth" is the main phenotype and "lag phase" is the variant). On the papers detail page, however, only the main phenotype is listed (e.g., "growth"). Can we provide the phenotype variant on the papers detail page too?

Here's a more concrete example. On the http://www.yeastphenome.org/conditions/ page, the condition "NaCl" is associated with 6 different variation of growth measurement. However, when I click on the individual papers, I don't see the variants any more.

**Comment by svenmh** [comment]
this should be fixed on yp-dev

**Comment by abarysh** [comment]
Looks good.
