### ISSUE TITLE
Remove sorting from the paper detail page

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#32]
Right now, the table that contains the datasets associated with each paper (e.g., http://www.yeastphenome.org/papers/98/) is sortable by any column. Working with some of the pages today I realized that those arrows (indicating that the table is sortable) is kinda annoying because most papers have very short tables (only 1 or a few datasets). Can we try and remove that arrow? And just sort the table by default by the columns as they appear in order? e.g. phenotypes, conditions, collection, tested genes, data type.

**Comment by svenmh** [comment]
Please check it out on http://yeastphenome-dev.princeton.edu

**Comment by abarysh** [comment]
Is the default sorting on, though? The table should always be sorted by column1, then column2, then column3, etc. From here (http://yeastphenome-dev.princeton.edu/papers/29/) it looks like it isn't yet?

**Comment by svenmh** [comment]
Ok, check it out again.

**Comment by abarysh** [comment]
Looks good.
