### ISSUE TITLE
Changing the link in admin page for phenotypes

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#33]
On this page http://www.yeastphenome.org/admin/phenotypes/phenotype/ the papers are linked to their front-end pages. Would it be possible to re-link them to their admin pages instead? To stay within the admin side of the website.

**Comment by svenmh** [comment]
Please check yeastphenome-dev.org

**Comment by abarysh** [comment]
Yep, works great.

**Comment by abarysh** [comment]
I don't think this works on the production server. Could you check it out?

**Comment by svenmh** [comment]
This is fixed, again.
