### ISSUE TITLE
Prevent Django from automatically naming new conditionsets

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#34]
In the admin interface, when a new conditionset is created or an old one is edited (e.g., http://www.yeastphenome.org/admin/conditions/conditionset/352/?_changelist_filters=q%3Dalanine), the name of the conditionset is automatically generated using the list of its conditions. Originally i thought it would simplify the process. But now I think we should remove that and name the conditions manually. The reason is because some conditionset (like the one I liked above) have too many components and their names would just be too long.

**Comment by svenmh** [comment]
I think I'm going to need a demo for this one.  When is a good time to stop by?

**Comment by svenmh** [comment]
try it out on yp-dev please.

**Comment by abarysh** [comment]
Could you look into #37 before I check this? This issue seems to be fixed but it's hard to tell for sure because all the formatting is off and I'm not 100% sure I'm looking at the same thing I saw on the production server.

**Comment by abarysh** [comment]
So I just tested it (after you fixed #37) and I don't think it works yet. Here's how I tested it:

- went to http://yeastphenome-dev.princeton.edu/admin/conditions/conditionset/
- clicked on "Add new condition set"
- chose 2 random conditions
- clicked "Save and continue editing" -- here it looks fine, the name is not added
- clicked "Save and continue editing" again -- the name is now set to the combination of the conditions are chose, even if I have written something else in the name field

**Comment by svenmh** [comment]
Woops, forgot to restart the server, try again.

**Comment by abarysh** [comment]
Yep, works now!
