### ISSUE TITLE
Enable to duplicate a condition set to create a new one

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#35]
It would be very useful to be able to create a new conditionset by duplicating an existing one and assigning it a new name. Ideally, on the conditionset edit page (e.g., http://www.yeastphenome.org/admin/conditions/conditionset/534/?_changelist_filters=q%3Dalanine) there would be a button (next to the Save buttons) that says "Duplicate" and opens up a new page with the same conditions selected (but not saved yet), so that the list can be edited and a new name for the conditionset can be chosen.

**Comment by svenmh** [comment]
on yp-dev there should now be an "Add condition set as..." button at the some place the "Add condition set" button is.  Please see if it's ok.

**Comment by abarysh** [comment]
Yep, this seems to work.

**Comment by svenmh** [comment]
now in production.
