### ISSUE TITLE
Admin: include the name of the condition set in the search

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#38]
When I search the conditionsets on http://yeastphenome-dev.princeton.edu/admin/conditions/conditionset/ , I don't think the name of the conditionset is currently included. For example, if I search "copy" it doesn't find anything even if I just created a bunch of test conditionsets with that name. Could we include the name in the search?

**Comment by svenmh** [comment]
does it do what you want now?  Check out yp-dev

**Comment by abarysh** [comment]
Yep, works great

**Comment by svenmh** [comment]
production is updated.
