### ISSUE TITLE
Add data & tested strains status to the admin paper list

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#39]
Could we add 2 new columns to this page:

http://www.yeastphenome.org/admin/papers/paper/

The columns would be the most recent data status and the most recent tested strains status (without the actual dates, to save space). The columns should be sortable, if possible. This way I can quickly get a list of papers with a certain status.

**Comment by svenmh** [comment]
I'm not sure if I going to be able to get them sortable, but did I get the correct columns?

**Comment by abarysh** [comment]
Yep, these are the right columns. I think we should be able to make them sortable. Django should allow that, as long as they are not functions.

**Comment by svenmh** [comment]
They are currently functions.

**Comment by abarysh** [comment]
Yeah, this feature in Django has always been tricky. Have you tried something similar to this https://docs.djangoproject.com/en/1.9/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_display (search for admin_order_field)

It looks like we might be able to get away with adding this to the PaperAdmin class:

```
def latest_data_status(self, obj):
    return obj.statusdata_set.latest
latest_data_status.admin_order_field = 'statusdata__status__status_name'
```

I can't test it, but let me know if you think it's promising. It would be really useful to be able to sort by those 2 fields.
