### ISSUE TITLE
Specify the types of data for papers marked as "to request"

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#44]
I'm catching up on sending emails to authors from which we might be able to get more complete data. But I've encountered several papers that are marked as "to request" but with little information about the datasets (e.g., PMID 24569176). Or also, cases where the datasets are all marked as "quantitative/quantitative/quantitative", so I'm not sure what info is missing and what should I be requesting from the authors. Could you fill in that info? Here's the list:

24569176
23358190
23964287
24040048

**Comment by bricha2** [comment]
I completed these! Let me known if you find any more! I will make sure to update the statuses if I change any more!
