### ISSUE TITLE
Collection in PMID: 25287021

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#46]
Right now it is marked as hap-alpha, but I was just glancing at the paper (to send the email request to the authors) and noticed that they say they used the BY4741 collection. Isn't that hap-a? I may be mixing them up but just wanted to double check with Christie, instead of changing it.

**Comment by ChristieChang** [comment]
The methods say BY4741 but list the genotype as MATalpha. Not sure which one is the typo. Maybe we need clarification from the authors?

"BY4741 strain (MATα his3Δ1 leu2Δ0 met15Δ0 ura3Δ0)" under Methods-Strains and growth media

**Comment by abarysh** [comment]
Yep, good point. I sent an email to the authors yesterday about the tested strains. I'll ask them about the mating type when they reply or when I send the second request (if they don't get back to be after a while). I'll make a note in the database.
