### ISSUE TITLE
Remove the Loaded/To request/etc. info from papers

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#6]
The last line in both "Tested genes available" and "Type of data" should probably be hidden (e.g., "Loaded", "To load", "To request","Requested"). It's our internal info, the users will probably have trouble understanding what it means, anyway.

**Comment by svenmh** [comment]
Hopefully this is fixed.

**Comment by abarysh** [comment]
It looks like this hasn't been fixed yet. Can we re-open the issue? (I don't think github lets me do it myself..)

**Comment by svenmh** [comment]
Feel free to reopen it, I'm doing it with with comment.  But guess I need a better description of what the issue is.

**Comment by abarysh** [comment]
Since we're going to simplify it substantially, I'll open a new issue.
