### ISSUE TITLE
FirstAuthor~LastAuthor, Year column 

### ISSUE THREAD

**Issue by abarysh** [svenmh/YeastPhenome.org#7]
On the paper list page (e.g., http://yeastphenome-dev.princeton.edu/papers/?s=mms ) let's make the columns wide enough to fit at least all the column headers. The longest column headers seem to be column 2 (FirstAuthor~LastAuthor, year) and the last one (Type of data).

**Comment by svenmh** [comment]
added text-nowrap to "FirstAuthor~LastAuthor, year".  Didn't do anything to "Type of data" as it isn't shown by default.
